version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "prgazevedo"
    assignees:
      - "prgazevedo"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 10
    # Group development dependencies
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "@typescript-eslint/*"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "fs-extra"
          - "simple-git"
    # Enable security updates
    allow:
      - dependency-type: "all"
    # Ignore specific packages if needed
    ignore:
      - dependency-name: "node"
        versions: ["< 16.0"]
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "prgazevedo"
    assignees:
      - "prgazevedo"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 5